// Authored and tested by Claude Code under the attentive guidance of
// Vladyslav Kozlovskyy <dbdevelop@gmail.com>, 2026.
// AGPL-3.0 — see LICENSE.

// Canonicalisation for text files synced by sync2.
//
// Locked policy:
//   - LF line endings universally (CRLF → LF, lone CR → LF).
//   - No leading UTF-8 BOM (decoded as the U+FEFF code point at index 0).
//   - Trailing newline iff the content is non-empty. Empty stays empty.
//
// Pure module: no I/O, no platform branching. Caller decides which paths
// pass through here (gated by `shouldCanonicalize(path, configDir)` below).

import { hasTextExtension } from "../utils";

export interface NormalizeResult {
  content: string;
  changed: boolean;
}

// Whether a path is eligible for canonicalization: a TEXT file the USER edits.
// Excludes `<configDir>/**` (e.g. `.obsidian/app.json`, `appearance.json`,
// `core-plugins.json`, and the plugin's own `manifest.json`/`styles.css`): those are
// AUTOGENERATED by Obsidian and the trailing-newline rule fights its own rewrites →
// pointless churn on files the user never sees. So canonicalization (CRLF→LF, BOM strip,
// trailing-NL) applies only to vault content the user actually edits. This is the SINGLE
// decision predicate for every byte-transforming canonicalize site (push enqueue, push
// merge, and the pull-side writeRemoteText) — they MUST agree, or a config file
// normalized on one side but passed raw on the other would re-sync forever.
//
// The `${configDir}/` prefix (with the slash) intentionally does NOT match a sibling
// like `.obsidian-notes/x.md` — only true children of the config dir.
export function shouldCanonicalize(path: string, configDir: string): boolean {
  return hasTextExtension(path) && !path.startsWith(`${configDir}/`);
}

const BOM_CODEPOINT = 0xfeff;

export function normalizeText(input: string): NormalizeResult {
  let s = input;
  if (s.length > 0 && s.charCodeAt(0) === BOM_CODEPOINT) {
    s = s.slice(1);
  }
  s = s.replace(/\r\n?/g, "\n");
  if (s.length > 0 && !s.endsWith("\n")) {
    s += "\n";
  }
  return { content: s, changed: s !== input };
}
