// Authored and tested by Claude Code under the attentive guidance of
// Vladyslav Kozlovskyy <dbdevelop@gmail.com>, 2026.
// AGPL-3.0 — see LICENSE.

// Canonicalisation for text files synced by sync2.
//
// Locked policy:
//   - LF line endings universally (CRLF → LF, lone CR → LF).
//   - No leading UTF-8 BOM (decoded as the U+FEFF code point at index 0).
//   - Trailing newline iff the content is non-empty. Empty stays empty.
//
// Pure module: no I/O, no platform branching. Caller decides which paths
// pass through here (gated by `shouldCanonicalize(path, configDir)` below).

import { hasTextExtension } from "../utils";

export interface NormalizeResult {
  content: string;
  changed: boolean;
}

// Whether a path is eligible for canonicalization: a TEXT file the USER edits.
// Excludes `<configDir>/**` (e.g. `.obsidian/app.json`, `appearance.json`,
// `core-plugins.json`, and the plugin's own `manifest.json`/`styles.css`): those are
// AUTOGENERATED by Obsidian and the trailing-newline rule fights its own rewrites →
// pointless churn on files the user never sees. So canonicalization (CRLF→LF, BOM strip,
// trailing-NL) applies only to vault content the user actually edits. This is the SINGLE
// decision predicate for every byte-transforming canonicalize site (push enqueue, push
// merge, and the pull-side writeRemoteText) — they MUST agree, or a config file
// normalized on one side but passed raw on the other would re-sync forever.
//
// The `${configDir}/` prefix (with the slash) intentionally does NOT match a sibling
// like `.obsidian-notes/x.md` — only true children of the config dir.
export function shouldCanonicalize(path: string, configDir: string): boolean {
  return hasTextExtension(path) && !path.startsWith(`${configDir}/`);
}

const BOM_CODEPOINT = 0xfeff;

// UTF-8 round-trip PROOF (NEW-DRAIN §II.15 / §12.9 principle: "size
// is an invitation, SHA is proof" — here "extension is an invitation,
// round-trip is proof"). Returns the decoded text when
// encode(decode(bytes)) reproduces the bytes EXACTLY, else null.
// Invalid UTF-8 under a text extension (a cp1251 .csv, a stray 0x80,
// a lone surrogate) decodes with U+FFFD substitutions and can never
// round-trip — the two silent-corruption paths this guards are
// inline tree content (§II.15) and text 3-way merges (_diff3).
export function utf8RoundTrip(bytes: ArrayBuffer): string | null {
  const text = new TextDecoder().decode(bytes);
  const back = new TextEncoder().encode(text);
  if (back.byteLength !== bytes.byteLength) return null;
  const a = new Uint8Array(bytes);
  for (let i = 0; i < a.length; i++) if (a[i] !== back[i]) return null;
  return text;
}

// Round-trip proof for the CANONICALIZE sites, which must SEE a
// leading BOM (normalizeText strips it deliberately). Plain
// utf8RoundTrip can't serve them: TextDecoder eats the BOM as an
// encoding signature, so encode(decode(bytes)) is 3 bytes short and
// the proof fails on every BOM file (gate finding 2026-08-31 —
// pull-of-bom-from-web). `ignoreBOM: true` keeps it as U+FEFF, which
// is exactly what the text-mode `adapter.read` on the push side
// yields, so both sides of the "three sites must agree" rule see the
// same string.
export function utf8RoundTripKeepBom(bytes: ArrayBuffer): string | null {
  const text = new TextDecoder("utf-8", { ignoreBOM: true }).decode(bytes);
  const back = new TextEncoder().encode(text);
  if (back.byteLength !== bytes.byteLength) return null;
  const a = new Uint8Array(bytes);
  for (let i = 0; i < a.length; i++) if (a[i] !== back[i]) return null;
  return text;
}

export function normalizeText(input: string): NormalizeResult {
  let s = input;
  if (s.length > 0 && s.charCodeAt(0) === BOM_CODEPOINT) {
    s = s.slice(1);
  }
  s = s.replace(/\r\n?/g, "\n");
  if (s.length > 0 && !s.endsWith("\n")) {
    s += "\n";
  }
  return { content: s, changed: s !== input };
}

export interface CanonicalBytes {
  // The bytes a commit records: the canonical encoding when `changed`,
  // otherwise the input buffer itself (no copy).
  bytes: ArrayBuffer;
  // True iff `bytes` differ from the input — i.e. the live file is not
  // canonical yet and a write-back is due.
  changed: boolean;
  // The canonical text when `changed` (what the write-back writes),
  // else null.
  content: string | null;
}

// COMMIT-PASS-PERF Крок 2 — the ONE canonical form of a file's bytes on
// the COMMIT side, shared by ChangeDetector (which hashes it) and
// BatchWriter (which records it). They must agree byte-for-byte, or the
// sha the detector proved and stored would not be the sha the batch
// names. `eligible` is the caller's gate: `shouldCanonicalize(path,
// configDir) && autoCanonicalize()`.
//
// Same round-trip PROOF as the pull-side write (vault-file-reader.ts,
// the §II.15 rule): bytes that are not valid UTF-8 under a text
// extension (a cp1251 .csv) pass through UNTOUCHED, never through a
// lossy decode. BOM-preserving decode, so normalizeText can see and
// strip the BOM.
export function canonicalizeBytes(
  bytes: ArrayBuffer,
  eligible: boolean,
): CanonicalBytes {
  const unchanged = { bytes, changed: false, content: null };
  if (!eligible) return unchanged;
  const text = utf8RoundTripKeepBom(bytes);
  if (text === null) return unchanged;
  const { content, changed } = normalizeText(text);
  if (!changed) return unchanged;
  const enc = new TextEncoder().encode(content);
  return {
    bytes: enc.buffer.slice(
      enc.byteOffset,
      enc.byteOffset + enc.byteLength,
    ) as ArrayBuffer,
    changed: true,
    content,
  };
}
